# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spaceship.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fspaceship.proto\"\xfc\x02\n\tSpaceship\x12\'\n\talignment\x18\x01 \x02(\x0e\x32\x14.Spaceship.Alignment\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x1f\n\x05\x63lass\x18\x04 \x02(\x0e\x32\x10.Spaceship.Class\x12\x0e\n\x06length\x18\x03 \x02(\x02\x12\x11\n\tcrew_size\x18\x05 \x02(\x05\x12\r\n\x05\x61rmed\x18\x06 \x02(\x08\x12$\n\x08officers\x18\x07 \x03(\x0b\x32\x12.Spaceship.Officer\x1a>\n\x07Officer\x12\x12\n\nfirst_name\x18\x01 \x02(\t\x12\x11\n\tlast_name\x18\x02 \x02(\t\x12\x0c\n\x04rank\x18\x03 \x02(\t\" \n\tAlignment\x12\x08\n\x04\x41lly\x10\x00\x12\t\n\x05\x45nemy\x10\x01\"]\n\x05\x43lass\x12\x0c\n\x08\x43orvette\x10\x00\x12\x0c\n\x08\x46riegate\x10\x01\x12\x0b\n\x07\x43ruiser\x10\x02\x12\r\n\tDestroyer\x10\x03\x12\x0b\n\x07\x43\x61rrier\x10\x04\x12\x0f\n\x0b\x44readnought\x10\x05\"+\n\nSpaceships\x12\x1d\n\tspaceship\x18\x01 \x03(\x0b\x32\n.Spaceship\"\x1b\n\x0b\x43oordinates\x12\x0c\n\x04\x63ord\x18\x01 \x03(\x02\x32W\n\x1e\x46\x65\x64\x65rationScannersAndDetectors\x12\x35\n\x15get_spacehips_in_area\x12\x0c.Coordinates\x1a\n.Spaceship\"\x00\x30\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spaceship_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SPACESHIP']._serialized_start=20
  _globals['_SPACESHIP']._serialized_end=400
  _globals['_SPACESHIP_OFFICER']._serialized_start=209
  _globals['_SPACESHIP_OFFICER']._serialized_end=271
  _globals['_SPACESHIP_ALIGNMENT']._serialized_start=273
  _globals['_SPACESHIP_ALIGNMENT']._serialized_end=305
  _globals['_SPACESHIP_CLASS']._serialized_start=307
  _globals['_SPACESHIP_CLASS']._serialized_end=400
  _globals['_SPACESHIPS']._serialized_start=402
  _globals['_SPACESHIPS']._serialized_end=445
  _globals['_COORDINATES']._serialized_start=447
  _globals['_COORDINATES']._serialized_end=474
  _globals['_FEDERATIONSCANNERSANDDETECTORS']._serialized_start=476
  _globals['_FEDERATIONSCANNERSANDDETECTORS']._serialized_end=563
# @@protoc_insertion_point(module_scope)
