# Generated by Django 4.2.6 on 2023-11-15 22:40

import app_music_upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_music_upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
        migrations.AlterField(
            model_name='blog',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[app_music_upload.models.validate_audio_file_extension]),
        ),
    ]
